name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        tag=$(date +%s)
        docker build . --file Dockerfile --tag singlestore-studio:${tag} 
        docker tag singlestore-studio:${tag} singlestore-studio:latest
